# Generated by Django 5.0.1 on 2024-02-02 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Giros',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cliente', models.CharField(max_length=100)),
                ('agregado', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
                ('billetera', models.CharField(choices=[('tigo-349', 'tigo-349'), ('tigo-757', 'tigo-757'), ('tigo-722', 'tigo-722'), ('zimple-349', 'zimple-349'), ('zimple-757', 'zimple-757'), ('zimple-722', 'zimple-722'), ('wally-349', 'wally-349'), ('wally-757', 'wally-757'), ('wally-722', 'wally-722')], max_length=100)),
                ('monto', models.IntegerField()),
                ('ref', models.CharField(max_length=100)),
                ('girosImg', models.ImageField(blank=True, null=True, upload_to='giros/')),
            ],
        ),
        migrations.CreateModel(
            name='Interfisa',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cliente', models.CharField(max_length=100)),
                ('agregado', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
                ('monto', models.IntegerField()),
                ('interfisaImg', models.ImageField(blank=True, null=True, upload_to='interfisa/')),
            ],
        ),
    ]
