# Generated by Django 5.0.1 on 2024-02-02 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transacciones', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='giros',
            name='ref',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
